#!/usr/bin/python

'''
Much of this code is derived from Shandy Brown's "Writing Games Tutorial". http://ezide.com/games/writing-games.html
Accessed 12/9/16: https://github.com/sjbrown/writing_games_tutorial/blob/example1/code_examples/example.py
tutorial@ezide.com
'''

from weakref import WeakKeyDictionary


def debug(msg):
    print(msg)


class Event:
    """this is a superclass for any events that might be generated by an
    object and sent to the EventManager"""

    def __init__(self):
        raise NotImplementedError("Class Event is an abstract base class and not intended for instantiation.")


class TickEvent(Event):
    def __init__(self):
        self.name = "Event — Tick"


class QuitEvent(Event):
    def __init__(self):
        self.name = "Event — Program Quit"


class MapGeneratedEvent(Event):
    def __init__(self, game_map):
        self.name = "Event — Map Finished Generating"
        self.map = game_map


class MapZoomEvent(Event):
    def __init__(self, zoom_level):
        self.name = "Event — Map Zoomed By {}px Per Tile".format(zoom_level)
        self.level = zoom_level


class GameStartedEvent(Event):
    def __init__(self, game):
        self.name = "Event — Game Started"
        self.game = game


class EventManager:
    """this object is responsible for coordinating most communication
    between the Model, View, and Controller."""

    def __init__(self):
        self.listeners = WeakKeyDictionary()
        self.event_queue = []

    def register_listener(self, listener):
        self.listeners[listener] = 1

    def unregister_listener(self, listener):
        if listener in self.listeners:
            del self.listeners[listener]

    def post(self, event):
        if not isinstance(event, TickEvent):
            debug("     Message: " + event.name)
        for listener in self.listeners:
            listener.notify(event)


class ClockController:
    """..."""

    def __init__(self, event_manager):
        self.event_manager = event_manager
        self.event_manager.register_listener(self)

        self.application_active = True

    def run(self):
        while self.application_active:
            event = TickEvent()
            self.event_manager.post(event)

    def notify(self, event):
        if isinstance(event, QuitEvent):
            # this will stop the while loop from running
            self.application_active = False
